console: add missing extern decl for limbo_sdl_scale_mode
This fixes a CI build error in ui/sdl2.c:524:
  error: use of undeclared identifier 'limbo_sdl_scale_mode'
  note: 'limbo_sdl_scale_hint' declared here

The variable was already defined in sdl2.c and declared in sdl2-2d.c,
but the shared __LIMBO__ block in console.h was missing the extern.